Update play_utils.py
Use importlib.resources instead of importlib_resources to prevent error AttributeError: module 'importlib_resources' has no attribute 'read_text'